this forceAddUniform "CUP_U_B_USMC_MARPAT_WDL_TwoKneepads";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_B_RRV_DA1";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_M67";};
for "_i" from 1 to 4 do {this addItemToVest "SmokeShell";};
this addItemToVest "hlc_200rnd_556x45_T_SAW";
this addBackpack "CUP_B_USMC_AssaultPack";
for "_i" from 1 to 2 do {this addItemToBackpack "hlc_200rnd_556x45_T_SAW";};
this addHeadgear "CUP_H_USMC_Headset_GoggleW_HelmetWDL";
this addWeapon "hlc_lmg_M249E2";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
